"use client";
import { useState } from "react";
import { Plus, Trash2, Save, LogOut } from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase-browser";

export default function AdminClient({initial}:{initial:any}){
 const [data,setData]=useState(initial); const [tab,setTab]=useState("components"); const [busy,setBusy]=useState(false);
 async function save(table:string,payload:any,id?:string){setBusy(true);const q=supabaseBrowser().from(table);const r=id?await q.update(payload).eq("id",id):await q.insert(payload);setBusy(false);if(r.error)alert(r.error.message);else location.reload();}
 async function remove(table:string,id:string){if(!confirm("Delete this item?"))return;const r=await supabaseBrowser().from(table).delete().eq("id",id);if(r.error)alert(r.error.message);else location.reload();}
 async function logout(){await supabaseBrowser().auth.signOut();location.href="/admin/login";}
 return <main className="mx-auto max-w-7xl px-5 py-8"><header className="flex items-center justify-between"><div><div className="text-sm text-white/35">World Best UI Components</div><h1 className="mt-1 text-3xl font-semibold">Admin</h1></div><button onClick={logout} className="glass flex items-center gap-2 rounded-xl px-4 py-2 text-sm"><LogOut size={15}/> Sign out</button></header>
 <div className="mt-8 flex gap-2 overflow-auto">{["components","versions","categories"].map(x=><button key={x} onClick={()=>setTab(x)} className={"rounded-full px-4 py-2 text-sm "+(tab===x?"bg-white text-black":"glass text-white/60")}>{x}</button>)}</div>
 {tab==="categories"&&<section className="mt-8"><button onClick={()=>save("categories",{name:"New Category",slug:"new-category",sort_order:data.categories.length+1,is_published:true})} className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-black"><Plus size={15} className="mr-1 inline"/> Add</button><div className="mt-4 space-y-2">{data.categories.map((c:any)=><div key={c.id} className="glass flex items-center gap-3 rounded-xl p-3"><input defaultValue={c.name} className="flex-1 bg-transparent outline-none" onBlur={e=>save("categories",{name:e.target.value},c.id)}/><button onClick={()=>remove("categories",c.id)}><Trash2 size={16}/></button></div>)}</div></section>}
 {tab==="components"&&<section className="mt-8"><button onClick={()=>save("components",{name:"New Component",slug:"new-component-"+Date.now(),description:"",preview_html:"<div style='font-family:sans-serif;padding:30px'>Preview</div>",is_published:false})} className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-black"><Plus size={15} className="mr-1 inline"/> Add component</button><div className="mt-4 grid gap-3">{data.components.map((c:any)=><div key={c.id} className="glass rounded-2xl p-4"><div className="flex items-center justify-between"><input defaultValue={c.name} className="bg-transparent text-lg font-medium outline-none" onBlur={e=>save("components",{name:e.target.value},c.id)}/><button onClick={()=>remove("components",c.id)}><Trash2 size={16}/></button></div><textarea defaultValue={c.description??""} onBlur={e=>save("components",{description:e.target.value},c.id)} className="mt-3 w-full rounded-xl bg-white/5 p-3 text-sm outline-none"/><label className="mt-3 flex items-center gap-2 text-sm text-white/55"><input type="checkbox" defaultChecked={c.is_published} onChange={e=>save("components",{is_published:e.target.checked},c.id)}/> Published</label></div>)}</div></section>}
 {tab==="versions"&&<section className="mt-8"><button onClick={()=>alert("Create a component first, then add a version using its UUID in Supabase. The API and schema support full versioned pricing/code.")} className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-black"><Plus size={15} className="mr-1 inline"/> Add version</button><div className="mt-4 grid gap-3">{data.versions.map((v:any)=><div key={v.id} className="glass flex items-center justify-between rounded-2xl p-4"><div><div className="font-medium">{v.components?.name} · {v.name}</div><div className="text-sm text-white/40">₹{v.price} · {v.is_free?"Free":"Paid"}</div></div><button onClick={()=>remove("component_versions",v.id)}><Trash2 size={16}/></button></div>)}</div></section>}
 <p className="mt-12 text-xs text-white/25">Changes are written directly through Supabase RLS. Server payment and code endpoints enforce ownership separately.</p></main>
}
